 ### POST /api/auth/signup
POST http://localhost:3001/api/auth/signup
Accept: */*
Content-Type: application/json

{
  "username":"조조",
  "password": "000000",
  "confirmPassword": "000000",
  "email": "dkd147@naver.com"
}

### POST /api/auth/signin
POST http://localhost:3001/api/auth/signin
Accept: */*
Content-Type: application/json

{
  "email": "bleaknightt@gmail.com",
"password":"000000"
}

### POST /api/auth/signout
POST https://localhost:3002/api/auth/signout
Accept: */*
Content-Type: application/json
