 ### GET /api/products
GET https://localhost:3002/api/products/
Accept: */*
Content-Type: application/json

### POST /api/products

POST http://localhost:3001/api/products/
Accept: */*
Content-Type: application/json

{
"name": "나와 동일한 이름",
"description": "??????????!",
"author": "뉴규뉴규",
"price": 2500
}

### PUT /api/products/:productId
PUT https://localhost:3002/api/products/12
Accept: */*
Content-Type: application/json

{
"name": "CU4567",
"description": "좋은 군것질이 많아서 좋아요!",
"status": "SOLD",
"price": 1500
}

### GET /api/products/:productId
GET https://localhost:3002/api/products/13
Accept: */*
Content-Type: application/json

### DELETE /api/products/:productId
DELETE https://localhost:3002/api/products/9
Accept: */*
Content-Type: application/json

### DELETE ALL /api/products/ - 관리자 권한 필요
DELETE https://localhost:3002/api/products/
Accept: */*
Content-Type: application/json


