### 내 정보 조회 API
GET https://localhost:3002/api/users/me
Accept: */*
Content-Type: application/json

###모든 사용자 조회 API
GET https://localhost:3002/api/users/
Accept: */*
Content-Type: application/json

###관리자 모드 - 관리자만 관리자 권한 부여
POST https://localhost:3002/api/users/11/admin
Accept: */*
Content-Type: application/json


// 내 정보 수정 API
PUT https://localhost:3002/api/users/me
Accept: */*
Content-Type: application/json

{
  "username":"조조",
  "password": "000000",
  "confirmPassword": "000000",
  "email": "bb@naver.com"
}

// 내 정보 삭제 API
GET https://localhost:3002/api/products/9
Accept: */*
Content-Type: application/json

//관리자 모드 - 모든 사용자 삭제 API
DELETE https://localhost:3002/api/users/me
Accept: */*
Content-Type: application/json

### DELETE ALL /api/products/ - 관리자 권한 필요
DELETE https://localhost:3002/api/users/
Accept: */*
Content-Type: application/json


